DROP DATABASE IF EXISTS test_rhc;
CREATE DATABASE test_rhc;
GRANT ALL ON test_rhc to 'test'@'%';
USE test_rhc;

CREATE TABLE IF NOT EXISTS `parent` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `foo` INT NOT NULL,
    `bar` INT,
    `chunk` BLOB NULL,
    PRIMARY KEY(`id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `child` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `parent_id` INT NOT NULL,
    `name` VARCHAR(100) NOT NULL,
    PRIMARY KEY(`id`),
	FOREIGN KEY(`parent_id`) REFERENCES `parent`(`id`)
) ENGINE=InnoDB;
